### PR TITLE
added html syntax for html inside strings

### PR DESCRIPTION
**Pull request by alesanchezr**
Hey man, I added support for syntax highlighting on HTML strings.

I need it because I'm teaching full-stack web development too ~400 students every year and I focus my teaching a lot on building HTML strings using python as a segue to front-end.

### CODE REVIEW

**Comment by alesanchezr** [comment]
@ptweir hey man, did you see this? What do you think??

**Comment by ptweir** [comment]
Thanks @alesanchezr ! I just merged the branch! I'm away from my computer this week, but next week I'll bump the version so that it is accessible via the vs code marketplace.

**Comment by alesanchezr** [comment]
@ptweir I did. But you closed the PR, should I open another?

**Comment by ptweir** [comment]
ah shoot, yes feel free to open another.

**Pull request merged**
